# -*- coding: utf-8 -*-
"""dealership_ai_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GrkJusNLrwpx-motSyC5lj3EFEQxQrA

# DEALERSHIP AI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

car_ai=pd.read_csv("CarPrice_Assignment.csv")
pd.set_option('display.max_columns',None)
car_ai['Brand'] = car_ai['CarName'].apply(lambda x: x.split(' ')[0].lower())
'''TO SPLIT THE BRAND NAME INTO TWO PARTS (FIRST HALF+SECOND HALF)'''
car_ai.drop('CarName', axis=1, inplace=True)

print(car_ai)

car_features=car_ai.iloc[:,[2,5,6,15,20,25]].values
car_dep=car_ai.iloc[:,24].values

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import joblib
import pandas as pd

ct = ColumnTransformer(
    transformers=[
        (
            'encoder',
            OneHotEncoder(
                sparse_output=False,
                handle_unknown="ignore"
            ),
            [0, 1, 2, 5]
        )
    ],
    remainder='passthrough'
)


encoded_array = ct.fit_transform(car_features)


encoded_cols = ct.get_feature_names_out()


hot_encoded = pd.DataFrame(encoded_array, columns=encoded_cols)


joblib.dump(encoded_cols, "feature_names.pkl")


print(hot_encoded.columns)

print(hot_encoded.shape)

from sklearn.model_selection import train_test_split
feature_train,feature_test,dep_train,dep_test=train_test_split(hot_encoded,car_dep,train_size=0.8,random_state=1)
print(feature_train.shape)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
feature_train.iloc[:, [37,38]] = sc.fit_transform(feature_train.iloc[:, [37,38]])
feature_test.iloc[:, [37,38]] = sc.transform(feature_test.iloc[:, [37,38]])



print(feature_train)

print(feature_test)

print(dep_train)

print(dep_test)

# model

from sklearn.ensemble import RandomForestRegressor
random_forest_reg=RandomForestRegressor(n_estimators=10,random_state=0)

random_forest_reg.fit(feature_train,dep_train)

pricepred=random_forest_reg.predict(feature_test)

from sklearn.metrics import r2_score
print("R2 Score:", r2_score(dep_test, pricepred))

import pickle
import joblib
joblib.dump(ct, "column_transformer.pkl")
joblib.dump(sc, "scaler.pkl")

joblib.dump(random_forest_reg, "car_price_model.pkl")
joblib.dump(encoded_cols, "feature_names.pkl")





